version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_DATABASE: 'fixtech'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    ports:
      - '3306:3306'
    expose:
      - '3306'